DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARDSEQ;

CREATE SEQUENCE CALBOARDSEQ;

--번호, ID, 제목, 내용, 일정(yyyyMMddhhmm), 작성날짜
CREATE TABLE CALBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(2000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL

);

SELECT * FROM CALBOARD;

-- row_number() over(partition by @ order by)
-- @로 group by 해서 그룹별 rownum 사용

SELECT *
FROM
	(SELECT (ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE))RN,
		SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
	FROM CALBOARD
	WHERE ID='kh' AND SUBSTR(MDATE,1,6)='201912'
	)
	

WHERE RN BETWEEN 1 AND 3;
ORDER BY MDATE;















